apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-log-app-deployment
spec:
  replicas: 2  # Number of desired replicas
  selector:
    matchLabels:
      app: time-log-app
  template:
    metadata:
      labels:
        app: go-web-app
    spec:
      containers:
        - name: time-log-app
          image: michalp96/time-log-app:1.0  # Replace with your Docker image name and tag
          ports:
            - containerPort: 8000  # Port your Go application is listening on
