# timelog-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-log-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: time-log-app
  template:
    metadata:
      labels:
        app: time-log-app
    spec:
      containers:
        - name: timelog-app
          image: michalp96/timelog-app:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000
          
